/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as HistoryExerciseIdRouteImport } from './routes/history.$exerciseId'
import { Route as TrainDayIdRouteImport } from './routes/train.$dayId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryExerciseIdRoute = HistoryExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => HistoryRoute,
} as any)
const TrainDayIdRoute = TrainDayIdRouteImport.update({
  id: '/train/$dayId',
  path: '/train/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/program': typeof ProgramRoute
  '/history/$exerciseId': typeof HistoryExerciseIdRoute
  '/train/$dayId': typeof TrainDayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/program': typeof ProgramRoute
  '/history/$exerciseId': typeof HistoryExerciseIdRoute
  '/train/$dayId': typeof TrainDayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/program': typeof ProgramRoute
  '/history/$exerciseId': typeof HistoryExerciseIdRoute
  '/train/$dayId': typeof TrainDayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/history' | '/program' | '/history/$exerciseId' | '/train/$dayId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/program' | '/history/$exerciseId' | '/train/$dayId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/program'
    | '/history/$exerciseId'
    | '/train/$dayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  ProgramRoute: typeof ProgramRoute
  TrainDayIdRoute: typeof TrainDayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$exerciseId': {
      id: '/history/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/history/$exerciseId'
      preLoaderRoute: typeof HistoryExerciseIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/train/$dayId': {
      id: '/train/$dayId'
      path: '/train/$dayId'
      fullPath: '/train/$dayId'
      preLoaderRoute: typeof TrainDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HistoryRouteChildren {
  HistoryExerciseIdRoute: typeof HistoryExerciseIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryExerciseIdRoute: HistoryExerciseIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRouteWithChildren,
  ProgramRoute: ProgramRoute,
  TrainDayIdRoute: TrainDayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
